### PR TITLE
Update en-GB.com_jedchecker.ini

### PR DESCRIPTION
**Pull request by conconnl**
One \ too much

### CODE REVIEW

**Comment by dryabov** [comment]
Both works, but `\\\"` seems to be more clear to me (escaped backslash followed by escaped double quote). I had to check sources of `zend_ini_scanner.l` file to be sure `\\"` is correctly processed as well.

**Comment by conconnl** [comment]
The current one in the file doesn’t work for other purposes, as it generates wrong translations in the processing system. 
This is also not how strings in Joomla are encoded.

**Comment by dryabov** [comment]
> The current one in the file doesn’t work for other purposes, as it generates wrong translations in the processing system.

Maybe it's a bug in the processing system that should be fixed, isn't it?

> This is also not how strings in Joomla are encoded.

I don't see any `\\"` in Joomla's ini files, so there is no exact match to check. Anyway, Joomla uses PHP's ini parser, and it supports both `\\\"` and `\\"`.

PS. I'd recommend to consider `\\&quot;` as an alternative, maybe it would work even better for translators.

**Comment by conconnl** [comment]
I can guarantee you for more then 1000% the string in this file is wrong and not the processing system. 

You can’t use &quot; at all. 

Every string has to use \” to display “ and escape them. 
This file is using \\\” while it should use \\” to display \” if you only want to display “ the string must use \”. 

The question is what should be displayed in the component according to you?

**Comment by dryabov** [comment]
The (sub)string `\"` (backslash followed by double quote) should be displayed to user.

From https://github.com/php/php-src/blob/master/Zend/zend_ini_scanner.l#L325-L333 one can see there are three characters (`"`, `\`, and `$`) that should be escaped in double-quoted ini string values, that's why it's necessary to write `\\\"` to get `\"` in output. The only reason of working `\\"` sequence comes from the loop-behind check (`YYCURSOR[-2] == '\\'`) at https://github.com/php/php-src/blob/master/Zend/zend_ini_scanner.l#L597, and any further refactoring there may lead to incorrect parsing of such strings (though it's very unlikely someone will try to change it in the near future).

**Comment by conconnl** [comment]
Exactly what I said!
You want to display `\"` to the user which means the language string should `\\"`
My correction makes that happen and solves the problem of the additional \ in the component and language strings.

**Comment by dryabov** [comment]
> You want to display `\"` to the user which means the language string should `\\"`

No. It should be either `\\\"` or `\\"`. I've just checked that both ways work identically in Joomla 3.9 and 4.0.

Could you give more details on where you see extra backslash with `\\\"`?

PS. There is another reason to consider working `\\"` as a PHP's glitch (apart from the fact that it's "not PHP way", because in PHP `$a="\\"";` results in the parse error and `$a="\\\"";` works well).

PHP has a possibility to use constants in values of parsed ini files, e.g. one can define a constant in PHP
```php
define('ACONST', 'test');
```
and then refer it in the ini file:
```ini
SOMEKEY = ACONST
```
It's also possible to build more complicated expressions, e.g. to prefix the value with a string:
```ini
SOMEKEY = "+" ACONST
```
that will result in `+test` value after the parsing. BUT if someone will try to use backslash as a prefix, it will not work:
```ini
SOMEKEY = "\\" ACONST
```
(neither `"\"` nor `"\\"` works here).

A similar problem is that there is no way to escape a dollar followed by open curvy brace:
```ini
SOMEKEY = "\${"
```
Surely it's a bug (coming from the fact that double quoted string is processed twice in https://github.com/php/php-src/blob/master/Zend/zend_ini_scanner.l: first time to get string length in `<ST_DOUBLE_QUOTES>[^]` lexer rule, and then to actually create string in `zend_ini_escape_string` function, and processing of escaped characters is not identical in both places).

Most likely, some day it will be fixed by PHP developers, and the fix will disallow sequences like `\\"`. Seems, none can refer to keeping backward compatibility here, because of lack of documentation about character escaping in the ini parser. The only I've found is the example on https://www.php.net/manual/en/function.parse-ini-file.php:
```ini
; \ is used to escape a value.
newline_is = "\\n" ; results in the string "\n", not a newline character.
with quotes = "She said \"Exactly my point\"." ; Results in a string with quote marks in it.
```
that is not fully correct, because `\n` sequence doesn't result in a newline character and may be kept unescaped.

**Comment by conconnl** [comment]
It's rather simple.
The message we want to tell developer is:
"Usage of \"_QQ_\" is deprecated since Joomla! 3.9. Use escaped double quotes (`\"`) instead"
To be able to show the slash (`\`) as well in the message we need too use `\\"`
The moment you use `\\\"` in the string, only one `\` will be used as escaped character.

You will never find `\\"` or `\\\"` anywhere in whatever string where the `"` is added.
It's not about thinking as a developer, but about how language strings in Joomla works.
The proofreaders, the language maintainers and others know better how this works.

Simply said, if we don't correct this, we have too remove the translation options, which will decrease the adoption.
While is as simply as removing the unnecessary `\`, as you said it works with `\\"`, so that solves all problems.

**Comment by dryabov** [comment]
The problem is that using the sequence `\\"` is an undocumented way (and I'm not sure it's a correct one).
I've send a related email (about the work of the PHP's ini lexer) to the PHP internals mailing list, let's wait for their response.

**Comment by dryabov** [comment]
My patch to PHP has been [merged](https://github.com/php/php-src/commit/d3a6054d4441a6d431e6ca7aa63de62cee5585c2), and so `\"` must be escaped as `\\\"`. I've checked that "legacy" sequence `\\"` is actually used in a few lines of the `it-IT.com_jedchecker.ini` translation:
```ini
COM_JEDCHECKER_CONGRATS="\"Congratulazioni Se si utilizza questo componente, allora avete molto probabilmente sviluppato una estensione di Joomla Ora arriva il &quot; duro &quot; parte - requisiti ottenerlo elencato nella Directory Estensione di Joomla (JED) La JED ha rigorose che devono. essere rispettate prima di un'estensione sarà pubblicato nella directory. Tali requisiti possono essere trovati <a href='%s' target='_blank'> qui </a>. Questo componente è stato costruito con l'obiettivo di semplificare lo sviluppo processo controllando automaticamente il codice per gli errori più comuni nelle estensioni \\"."

COM_JEDCHECKER_ERROR_XML_LICENSE_NOT_GPL="\"Si prega di verificare se la licenza in questo file è compatibile con la GPL\\"."

COM_JEDCHECKER_RULE_ENCODING_DESC="\"Come sviluppatori siamo pienamente consapevoli che la Base64 e funzioni simili hanno un posto valido estensioni (come URL reindirizza o la memorizzazione dei dati). Tuttavia, se si utilizzano quelli per rendere più difficile per gli utenti di leggere il codice o per mascherare ritroso il JED non accetterà la vostra presentazione messa in vendita (questo non è nello spirito della GPL comunque!). Un redattore rivedrà il codice e determinare se il modo in cui si utilizza il base64 corrisponde alle regole del JED. questo potrebbe rallentare la tua opinione tempo listing . Quindi la regola generale è - non fare cose di pesce ed evitare la codifica del codice, se possibile \\"!"

COM_JEDCHECKER_RULE_PH1_DESC="\"Un avviso è richiesto su ogni file PHP che indica che il file è licenziato GPL (o altra licenza accettato compatibile) Per ulteriori informazioni, si prega di <a href='http://extensions.joomla.org/support/knowledgebase/item/jed-entries-checklists#licensechecklist' target='_blank'> clicca qui </a> \\"."

COM_JEDCHECKER_OLD_RULE_X_PHP_FILE_REMOVED="\"file PHP Rimosso per '%s' regola\\"."

COM_JEDCHECKER_RULE_US1_DESC="\"L'uso di Update Server è ora richiesto da Jed\\"."
```

I'm not sure those extra quotations are necessary at all (original `en-GB` strings don't contain them), but I'm almost sure there should be no backslash at the end of above sentences.

@Llewellynvdm Do you have access to these strings on Crowdin to fix this issue (by removing wrapping `\"` quotes inside of strings, or at least by escaping the trailing quote properly as `\\\"` instead of `\\"`)?

**Comment by dryabov** [comment]
BTW, in the PR #122, the string with `\\\"` is changed to
```ini
COM_JEDCHECKER_LANG_QQDEPRECATED="Usage of &quot;&#95;QQ&#95;&quot; is deprecated since Joomla! 3.9. Use escaped double quotes (\\&quot;) instead"
```
specifically to prevent counting of backslashes by translators (note: `&#95;` is used instead of `_` as a trick to process JEDChecker sources with JEDChecker without error messages, but probably it would be simple to replace encoded `"_QQ_"` by `%s` and print it via `sprintf`).

**Pull request closed without merging**
