### PR TITLE
Don't require _JEXEC guard for files with class declaration only

### PR DESCRIPTION
**Pull request by dryabov**

### CODE REVIEW

**Comment by anibalsanchez** [comment]
Please, note that the rule is PH2 https://extensions.joomla.org/support/knowledgebase/error-codes/submission-error-codes/

**PH2 - Files missing JEXEC security
Security is extremely important in Open Source Software, so to help prevent the execution of files outside of the framework, the following code is required in all of your PHP files unless they are external library files**

It can't be merged without changing the rule.

Please, submit your request to the JED team. 

CC: @conconnl

**Comment by dryabov** [comment]
> Please, submit your request to the JED team.

Where? `jed-issues` repo?

**Comment by anibalsanchez** [comment]
Yes, that is a good starting point: https://github.com/joomla/jed-issues/issues

Please, note that all Joomla core classes have "defined('_JEXEC') or die;" so JED is hardly going to go against a general Joomla CMS practice.

**Comment by dryabov** [comment]
> Please, note that the rule is PH2 https://extensions.joomla.org/support/knowledgebase/error-codes/submission-error-codes/

@anibalsanchez BTW, do you have access to editing of that article? There is line feed missed in the code example

    // no direct access defined( '_JEXEC' ) or die( 'Restricted access' );

**Comment by dryabov** [comment]
Done: https://github.com/joomla/jed-issues/issues/215

**Comment by anibalsanchez** [comment]
Following @Llewellynvdm definitions in the https://github.com/joomla/jed-issues/issues/215, I'm closing this PR.

**Pull request closed without merging**
