### PR TITLE
Update da-DK.com_jedchecker.ini

### PR DESCRIPTION
**Pull request by rbuelund**
Updated most of the danish language strings. Feel free to comment on the new strings.

### CODE REVIEW

**Comment by conconnl** [comment]
Translations for languages happen in https://joomla.Crowdin.com/

They are automatically processed, any change in the files on the repository will be overwritten by Crowdin. 

Please provide translations and / or suggestions in Crowdin.

**Comment by rbuelund** [comment]
Ahh ok - how do I get access to translate on joomla.crowdin.com ??

**Comment by rbuelund** [comment]
Ok - I managed to get the updated translations on the crowdin project - but who is gonne review the strings - I am not allowed to... ?

**Comment by conconnl** [comment]
The proofreaders will do that in the future. 
They also do the CMS and such. 
The PR is already created see:
https://github.com/joomla-extensions/jedchecker/pull/93

**Comment by rbuelund** [comment]
Ok, so there are danish proofreaders attached to the project on Crowdin ??

**Comment by conconnl** [comment]
> Ok, so there are danish proofreaders attached to the project on Crowdin ??

Like I said, the proofreaders will do that in the future. Please have a little bit patient and you will see the mail shortly as TT coordinator.

**Comment by rbuelund** [comment]
Ohh it is not because I am in a hurry - I am just wondering about this platform, which I have never met before as a danish translation coordinator... ;-)

**Comment by conconnl** [comment]
You will in a few days / weeks 😜

**Pull request closed without merging**
