### PR TITLE
Add error-level badges

### PR DESCRIPTION
**Pull request by dryabov**
Fix issue #154.

### CODE REVIEW

**Comment by conconnl** [comment]
Did you add the font-awesome default icons in front of it?

**Comment by dryabov** [comment]
> Did you add the font-awesome default icons in front of it?

No.

I tried to add Bootstrap icons as SVG (the FontAwesome SVG icons are released under CC BY 4.0 and require to indicate all changes made, even if it's just a change of width/height attributes, and Bootstrap icons are MIT licensed), but the result doesn't look good (IMHO), mostly because of the varying heights of alert blocks (I tried both top and center vertical alignment). And they are quite annoying in the case of long issue lists.

**Comment by conconnl** [comment]
Joomla Core uses Font-Awesome for what I have seen. It should not be a problem too use it. Could you check to be sure?

**Comment by dryabov** [comment]
Joomla 3 is shipped with IcoMoon icons, and Joomla 4 has FontAwesome instead. I wouldn't like to have two different code branches for different Joomla versions to just display an icon (that will consume significant part of screen width on mobiles).

**Comment by anibalsanchez** [comment]
In similar cases, I use to embed the SVGs. It is only a few Kbs and 4 files.

**Pull request merged**
